apiVersion: v1
kind: Service # Creating an object of type Service.
metadata:
  name: client-node-port
spec:
  type: NodePort # subtype of object Service
  ports:
  - port: 3050 # this port can be used by any other container/pod inside the application in order to access  multiclient pod.
    targetPort: 3000 # this should be same as containerPort of the pod object.
    nodePort: 31515 # (optional, one will be randomly assigned) this is a random port in the range of 30000 - 32767. This will be exposed to the external world. this will be typed along with ip to access the multiclient pod.
  selector:
    component: web # this is a label selector, it's value should be the same as  'metadata.labels.component' to which this object is refering to. Keyword component can be changed to any arbitary value. We just have to make sure its the same.