apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
      - name: postgres
        image: postgres
        ports:
          - containerPort: 5432 # port on which the application is running and is exposed
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgpassword
                key: PGPASSWORD
        volumeMounts:
          - name: postgres-storage # volume name and volume mount should be identical
            mountPath: /var/lib/postgresql/data # this is the path where postgres store the data, and we are mounting it to a pv
            subPath: postgres # folder inside the persistent volume where we want to mount the path, i.e all the data from /var/lib/postgresql/data will be present at /postgres
