apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
spec:
  type: ClusterIP # this cannot have nodePort property in ports section.
  selector:
    component: redis
  ports:
    - port: 6379 # this port can be used by any other container/pod inside the application in order to access  multiclient pod.
      targetPort: 6379 # this should be same as containerPort of the pod object.