apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP # this cannot have nodePort property in ports section.
  selector:
    component: server
  ports:
    - port: 5000 # this port can be used by any other container/pod inside the application in order to access  multiclient pod.
      targetPort: 5000 # this should be same as containerPort of the pod object.