apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      comopnent: server
  template:
    metadata:
      labels:
        comopnent: server
    spec:
      containers:
      - name: server
        image: stephengrider/multi-server
        ports:
        - containerPort: 5000 # port on which the application is running and is exposed